export const SEED_LOCATIONS = [
  { name: "1010 Brickell Condominiums", address: "1010 Brickell Avenue, Miami, FL 33131", contact: "", email: "", phone: "" },
  { name: "500 Brickell Master Association", address: "500 Brickell Ave, Miami, FL, 33131", contact: "Angel Agramonte", email: "agramonte@fpisecurity.com", phone: "+1(954) 516-8420" },
  { name: "900 Biscayne Bay Condominium", address: "900 Biscayne Bay Blvd Miami, FL 33132", contact: "Rafael Solis", email: "rsolis@kwpmc.com", phone: "786-320-1537" },
  { name: "A+ Mini Storage", address: "1851 Delaware Parkway, Miami, FL 33125", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Ateco", address: "4851 NW 128 Street, Opa Locka, FL 33054", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "AutoNation Ford Miami", address: "16800 NW 57 Avenue, Hialeah, FL 33015", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "AutoNation Honda Hollywood", address: "2400 N State Road 7, Hollywood, FL 33021", contact: "", email: "", phone: "" },
  { name: "AutoNation Land Rover/Mercedes", address: "400 W Copans Road, Pompano Beach, FL 33064", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Blue Lagoon Condominium Association", address: "", contact: "Renold Berice", email: "berice@fpisecurity.com", phone: "305-300-7622" },
  { name: "Brickell Flat Iron Condominium", address: "1000 Brickell Plz, Miami, FL, 33131", contact: "Angel Agramonte", email: "", phone: "" },
  { name: "Century Village Pembroke Pines", address: "13300 SW 10 Street, Pembroke Pines, FL", contact: "Veronica Vasquez", email: "Vvasquez@fpisecurity.com", phone: "" },
  { name: "City Of Pompano Beach East District", address: "501 Dr. Martin Luther King Jr Blvd, Pompano Beach, FL 33060", contact: "Berice Renolds", email: "berice@fpisecurity.com", phone: "3053007622" },
  { name: "City Of Pompano Beach Northwest District", address: "501 Dr. Martin Luther King Jr Blvd, Pompano Beach, FL 33060", contact: "Berice Renolds", email: "berice@fpisecurity.com", phone: "3053007622" },
  { name: "City of Coral Gables", address: "Coral Gables, FL.", contact: "", email: "berice@fpisecurity.com", phone: "" },
  { name: "City of Fort Lauderdale", address: "", contact: "", email: "rlopez@fpisecurity.com", phone: "" },
  { name: "City of Miami Beach", address: "1700 Convention Center Dr., Miami Beach, FL 33139", contact: "", email: "", phone: "13056737000" },
  { name: "City of Pembroke Pines", address: "", contact: "", email: "", phone: "" },
  { name: "Coral Reef Yacht Club", address: "2484 S Bayshore Dr, Miami, FL 33133", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "Design Place Apartments", address: "", contact: "", email: "", phone: "" },
  { name: "Estancia", address: "100 SW 186th Avenue, Pembroke Pines, FL 33029", contact: "", email: "", phone: "" },
  { name: "Ferarri Maserati", address: "5750 N Federal Highway, Fort Lauderdale, FL 33308", contact: "", email: "", phone: "" },
  { name: "Fiveash Water Plant", address: "949 NW 38 Street, Fort Lauderdale, FL 33309", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "FPI Office", address: "1771 N Flamingo Road", contact: "Daniel Gonzalez", email: "dgonzalez@fpisecurity.com", phone: "+1(954) 370-5300" },
  { name: "FPI Office - Pool Car", address: "", contact: "", email: "", phone: "" },
  { name: "Gibson Truck World", address: "3455 S Orlando Drive, Sanford, FL 32773", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Greico Ford/Chevrolet", address: "1333 N Federal Hwy, Fort Lauderdale, FL 33304", contact: "Peter", email: "Pweimar@fpisecurity.com", phone: "" },
  { name: "Grieco Ford & Chevrolet", address: "1333 N Federal Hwy, Fort Lauderdale, FL 33304-1427", contact: "", email: "", phone: "" },
  { name: "Headquarter Honda", address: "17700 State Road 50, Clermont, FL 34711", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Headquarter Toyota", address: "5895 NW 167 Street, Hialeah, FL 33015", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Imagination Farms", address: "", contact: "", email: "", phone: "" },
  { name: "Jaguar Treasure Coast", address: "4771 S US Highway 1, Fort Pierce, FL 37982", contact: "Renold Berice", email: "berice@fpisecurity.com", phone: "+1 (305) 300-7622" },
  { name: "Miami Beach Biscayne Beach (Stillwater)", address: "960 Stillwater Dr, Miami Beach, FL 33141", contact: "", email: "", phone: "" },
  { name: "Miami Beach Homeless Outreach", address: "555 17th St, Miami Beach, FL 33139", contact: "", email: "", phone: "" },
  { name: "Monsignor Pace High School", address: "15600 NW 32 Avenue, Opa Locka, FL 33054", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "Montesorri Academy", address: "19200 Pines Blvd", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "My Brickell Condo Association", address: "31 SE 6th St, Miami, FL 33131", contact: "", email: "", phone: "" },
  { name: "North Lakes in Weston", address: "", contact: "", email: "", phone: "" },
  { name: "ONTIC MRO", address: "15701 SW 29th St Ste 100a, Miramar, FL 33027", contact: "", email: "", phone: "" },
  { name: "Ocean Bank - Main Branch", address: "", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "Ocean Bank - Miami Beach Branch", address: "501 Arthur Godfrey Road, FL 33140", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "Opal Creek", address: "", contact: "", email: "", phone: "" },
  { name: "Palmetto 57 Nissan", address: "16725 NW 57 Avenue, Opa Locka, FL 33055", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Parking Rover", address: "2801 Salzedo St, Coral Gables, FL 33146", contact: "Renold Berice", email: "berice@fpisecurity.com", phone: "" },
  { name: "Pembroke Falls", address: "1651 NW 136th Avenue, Pembroke Pines, FL 33028", contact: "", email: "", phone: "" },
  { name: "Pembroke Pines Academic Village", address: "", contact: "", email: "", phone: "" },
  { name: "Pines Department/Human Services", address: "", contact: "", email: "", phone: "" },
  { name: "Pines Place", address: "8203 S Palm Drive, Pembroke Pines, FL 33025", contact: "Peter Weimar", email: "Pweimar@fpisecurity.com", phone: "" },
  { name: "Poinciana Parc", address: "", contact: "", email: "", phone: "" },
  { name: "Polynesian at Island at Doral", address: "11440 NW 75 Terrace, Medley, FL 33178", contact: "Radames", email: "rlopez@fpisecurity.com", phone: "954 701-8125" },
  { name: "Recovery Performance Marine", address: "3800 NW 27 Avenue, Miami, FL 33142", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Rick Case Plantation", address: "925 North State Road 7, Fort Lauderdale, FL 33317", contact: "", email: "", phone: "" },
  { name: "Sawgrass Ford", address: "14501 W Sunrise Blvd, Sunrise, FL 33323", contact: "Berice", email: "Berice@fpisecurity.com", phone: "" },
  { name: "Sebal Chase Homeowners Association", address: "10999 SW 113th Place, Miami, FL 33176", contact: "Agramonte Angel", email: "agramonte@fpisecurity.com", phone: "954 516 8420" },
  { name: "Silver Lakes Phase 4", address: "", contact: "", email: "", phone: "" },
  { name: "Silver Shores Master Association", address: "15601 Silver Shores Blvd, Hollywood, FL 33027", contact: "", email: "", phone: "" },
  { name: "SilverLakes", address: "978 NW 178 Avenue, Pembroke Pines, FL 33027", contact: "", email: "", phone: "954-205-1872" },
  { name: "South Florida Auto Auction", address: "3500 NW 21st St, Lauderdale Lakes, FL 33311", contact: "", email: "", phone: "" },
  { name: "St. Andrews Condominium", address: "12100 Saint Andrews Place, Miramar, FL 33025", contact: "Radames", email: "rlopez@fpisecurity.com", phone: "" },
  { name: "Storage Lot", address: "10801 Pembroke Road, Pembroke Pines, FL 33025", contact: "Peter Weimar", email: "Pweimar@fpisecurity.com", phone: "" },
  { name: "Ten Aragon Condominium", address: "10 Aragon Avenue, Coral Gables, FL 33134", contact: "", email: "", phone: "" },
  { name: "The Crosby Miami World Center", address: "698 NE 1st Ave, Miami, FL 33132", contact: "", email: "", phone: "" },
  { name: "The Villages of San Messina", address: "", contact: "", email: "", phone: "" },
  { name: "Vizcaya HOA", address: "", contact: "", email: "", phone: "" },
  { name: "Water Treatment Plant", address: "7960 Johnson Street, Pembroke Pines, FL 33024", contact: "Peter Weimar", email: "Pweimar@fpisecurity.com", phone: "" },
  { name: "West Early Development Center", address: "1600 SW 184th Ave, Hollywood, FL 33029", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "9546001858" },
  { name: "Westminster Academy", address: "5601 N. Federal Highway", contact: "Don Cannella", email: "dcannella@fpisecurity.com", phone: "954-771-4615" },
  { name: "Westminster Academy Little Ridge", address: "", contact: "Def Andre", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "Westminster Academy Main Campus", address: "", contact: "", email: "dandre@fpisecurity.com", phone: "+1 (954) 600-1858" },
  { name: "White Rock Quarries North", address: "18300 NW 122 Avenue, Hialeah, FL 33018", contact: "", email: "", phone: "" },
];
